language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - pypy

install:
  # -- DISABLED: pip install --use-mirrors -q -U pytest
  - python setup.py -q install
script:
  - python --version
  - py.test tests
